# Generated by Django 3.2 on 2022-05-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoxitWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('salary', models.FloatField()),
                ('favorite_joke', models.TextField()),
            ],
            options={
                'db_table': 'coxit_workers',
            },
        ),
    ]
