# Generated by Django 3.2 on 2022-05-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coxit_staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'coxit_positions',
            },
        ),
        migrations.CreateModel(
            name='WorkerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Tr', 'Trainee'), ('Jr', 'Junior'), ('Md', 'Middle'), ('Sr', 'Senior')], default='Jr', max_length=2)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coxit_staff.position')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coxit_staff.coxitworker')),
            ],
            options={
                'db_table': 'worker_position_rel',
            },
        ),
    ]
