# Generated by Django 3.2 on 2022-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coxit_staff', '0003_alter_coxitworker_favorite_joke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coxitworker',
            name='favorite_joke',
            field=models.TextField(blank=True, null=True),
        ),
    ]
